export const actionType = {
    COMPANY_LOGO_LEFT: "COMPANY_LOGO_LEFT",
    PRESET_COLOR: "PRESET_COLOR",
    CONTINUE_BUTTON: "CONTINUE_BUTTON",
    COLOR_CHANGE: "COLOR_CHANGE",
    SHOW_HEADER: 'SHOW_HEADER',
    SHOW_FOOTER: "SHOW_FOOTER",
    LEFT_DRAWER:"LEFT_DRAWER",
    RIGTH_DRAWER:"RIGTH_DRAWER",
    SHOW_TABS:"SHOW_TABS",
    SHOW_MENU:"SHOW_MENU"
}